/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adamperclient;

import java.awt.*;
import java.io.*;
import java.net.*;
import java.util.logging.*;
import javax.imageio.*;
import msg.*;

/**
 *
 * @author adamp
 */
public class Login extends javax.swing.JFrame {
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Login(null).setVisible(true);
      }
    });
  }
  
  /**
   * Creates new form Login
   */
  public Login(AdamperChat frame) {
    _mainFrame = frame;
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/adamperclient/icon.png")));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nickField = new javax.swing.JTextField();
    nickLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    passwordField = new javax.swing.JTextField();
    loginBtn = new javax.swing.JButton();
    mainTitle = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Log in to AdamperChat");
    setIconImage(getIconImage());
    setMinimumSize(new java.awt.Dimension(440, 250));
    setName("loginFrame"); // NOI18N
    setPreferredSize(new java.awt.Dimension(440, 270));
    setResizable(false);
    setSize(new java.awt.Dimension(440, 270));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    nickLabel.setText("Twój nick:");

    passwordLabel.setText("Twoje hasło:");
    passwordLabel.setEnabled(false);

    passwordField.setEditable(false);

    loginBtn.setText("Zaloguj się");
    loginBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginBtnActionPerformed(evt);
      }
    });

    mainTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
    mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    mainTitle.setText("AdamperChat");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(mainTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGap(70, 70, 70)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(nickLabel)
              .addComponent(nickField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(passwordLabel)
              .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(loginBtn))
            .addGap(0, 74, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(nickLabel)
        .addGap(5, 5, 5)
        .addComponent(nickField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(15, 15, 15)
        .addComponent(passwordLabel)
        .addGap(5, 5, 5)
        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(15, 15, 15)
        .addComponent(loginBtn)
        .addGap(30, 30, 30))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    String nick = nickField.getText().trim();
    
    boolean loggedIn = false;
    String resp = "";
    if(!nick.equals("") && nick.length() > 3) {
      Socket socket;
      InputStreamReader streamreader = null;
      Message tempMsg;

      try {
        socket = new Socket(_mainFrame.getHost(), _mainFrame.getPort());
        streamreader = new InputStreamReader(socket.getInputStream());
        BufferedReader reader = new BufferedReader(streamreader);
        PrintWriter writer = new PrintWriter(socket.getOutputStream());
        
        tempMsg = new Message(MsgType.Login, nick, "LoginMsg");
        writer.println(tempMsg.getMessage());
        writer.flush();
        
        boolean out = false;
        int i = 0;
        String stream;
        while ((stream = reader.readLine()) != null) {
          Message receivedMsg = new Message(stream);
          switch(receivedMsg.getType()) {
            case Connect:
              loggedIn = true;
              resp = receivedMsg.getContent();
              out = true;
              break;
            case Disconnect:
              loggedIn = false;
              resp = receivedMsg.getContent();
              out = true;
              break;
          }
          i++;
          if(i > 200) { break; }
          if(out) { break; }
        }

      } catch (IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Błąd połączenia. - 1");
      } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Błąd połączenia. - 2");
      }
    }
    
    if(!nick.equals("") && nick.length() > 3 && loggedIn) {
      _mainFrame.setUsername(nick);
      _mainFrame.setAutoRequestFocus(true);
      _mainFrame.setEnabled(true);
      this.setVisible(false);
    } else if(nick.equals("") || nick.length() <= 3 && !loggedIn) {
      javax.swing.JOptionPane.showMessageDialog(null, "Nick musi być dłuższy niż 3 litery.");
    } else if(!resp.equals("") && !loggedIn) {
      javax.swing.JOptionPane.showMessageDialog(null, resp.trim());
    }
  }//GEN-LAST:event_loginBtnActionPerformed
  
  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    this.setVisible(false);
  }//GEN-LAST:event_formWindowClosed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.setVisible(false);
  }//GEN-LAST:event_formWindowClosing

  private AdamperChat _mainFrame = null;
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton loginBtn;
  private javax.swing.JLabel mainTitle;
  private javax.swing.JTextField nickField;
  private javax.swing.JLabel nickLabel;
  private javax.swing.JTextField passwordField;
  private javax.swing.JLabel passwordLabel;
  // End of variables declaration//GEN-END:variables
}
