/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adamperclient;

import java.awt.*;
import java.io.*;
import java.net.*;
import java.util.logging.*;
import javax.imageio.*;
import javax.swing.*;

import msg.*;

/**
 *
 * @author adamp
 */
public class LoginBox extends javax.swing.JFrame {

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(LoginBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(LoginBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(LoginBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(LoginBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new LoginBox(null).setVisible(true);
      }
    });
  }

  /**
   * Creates new form Login
   */
  public LoginBox(AdamperChat frame) {
    _mainFrame = frame;
    initComponents();
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/adamperclient/icon.png")));
  }

  private void login() {
    String username = usernameField.getText().trim();
    String responseMsg = "";
    Message tempMsg = null;

    if (!checkNick(username)) {
      errorAlert("Nick musi być dłuższy niż 3 litery.");
      return;
    }

    try {
      socket = new Socket(_mainFrame.getHost(), _mainFrame.getPort());
      reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
      writer = new PrintWriter(socket.getOutputStream());

      tempMsg = new Message(MsgType.Login, username, "LoginMsg");
      writer.println(tempMsg.getMessage());
      writer.flush();

      boolean out = false;
      String stream;
      int i = 0;
      while ((stream = reader.readLine()) != null) {
        Message receivedMsg = new Message(stream);
        switch (receivedMsg.getType()) {
          case Connect:
            _loggedIn = true;
            responseMsg = receivedMsg.getContent();
            out = true;
            break;
          case Disconnect:
            _loggedIn = false;
            responseMsg = receivedMsg.getContent();
            out = true;
            break;
        }
        i++;
        
        if (out || i > 200) {
          break;
        }
      }

    } catch (IOException ex) {
      errorAlert("Błąd połączenia. (1)");

    } catch (Exception ex) {
      errorAlert("Błąd połączenia. (2)");
    }
    
    setLoginResults(username, responseMsg);
  }

  private void setLoginResults(String username, String responseMsg) {
    if (checkNick(username) && _loggedIn) {
      _mainFrame.setUsername(username);
      _mainFrame.setAutoRequestFocus(true);
      _mainFrame.setEnabled(true);
      this.setVisible(false);

    } else if (!checkNick(username) && !_loggedIn) {
      errorAlert("Nick musi być dłuższy niż 3 litery.");

    } else if (!responseMsg.equals("") && !_loggedIn) {
      errorAlert(responseMsg.trim());
    }
  }

  private boolean checkNick(String nick) {
    return !nick.equals("") && nick.length() > 3;
  }

  private void errorAlert(String text) {
      JOptionPane.showMessageDialog(this, text.trim(), "Błąd", JOptionPane.INFORMATION_MESSAGE);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    usernameField = new javax.swing.JTextField();
    usernameLabel = new javax.swing.JLabel();
    loginBtn = new javax.swing.JButton();
    mainTitle = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Logowanie AdamperChat");
    setIconImage(getIconImage());
    setMinimumSize(new java.awt.Dimension(440, 250));
    setName("loginFrame"); // NOI18N
    setPreferredSize(new java.awt.Dimension(440, 270));
    setResizable(false);
    setSize(new java.awt.Dimension(440, 270));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    usernameLabel.setText("Twoja nazwa użytkownika:");

    loginBtn.setText("Zaloguj się");
    loginBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginBtnActionPerformed(evt);
      }
    });

    mainTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
    mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    mainTitle.setText("AdamperChat");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(70, 70, 70)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(usernameLabel)
          .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(loginBtn))
        .addContainerGap(84, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(mainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(usernameLabel)
        .addGap(5, 5, 5)
        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(25, 25, 25)
        .addComponent(loginBtn)
        .addGap(20, 20, 20))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    login();
  }//GEN-LAST:event_loginBtnActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    this.setVisible(false);
  }//GEN-LAST:event_formWindowClosed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.setVisible(false);
  }//GEN-LAST:event_formWindowClosing

  private AdamperChat _mainFrame = null;
  private boolean _loggedIn = false;

  Socket socket = null;
  BufferedReader reader = null;
  PrintWriter writer = null;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton loginBtn;
  private javax.swing.JLabel mainTitle;
  private javax.swing.JTextField usernameField;
  private javax.swing.JLabel usernameLabel;
  // End of variables declaration//GEN-END:variables
}
